language: python
python:
  - '2.7'
script: ./unittests
deploy:
  provider: lambda
  function_name: VASOS
  region: us-east-1
  role: arn:aws:iam::984814083532:role/lambda_basic_execution
  runtime: python3.6
  module_name: alexa_py
  handler_name: lambda_handler
  zip: ./src
  access_key_id: AKIAJULVACVMKHJUMH7A
  on:
    branch: master
  secret_access_key:
    secure:
